version: '0'
services:
  mongo:
    image: mongo:latest
    container_name: bot-mongo
    ports:
      - "27017:27017"
    volumes:
      - myvolume:/data/db
    networks:
      - mynetwork

  discord-bot:
    image: discord-bot:latest
    container_name: bot-client
    depends_on:
      - mongo
    networks:
      - mynetwork
    stdin_open: true
    tty: true


volumes:
  myvolume:

networks:
  mynetwork: