version: '0'
services:
  mongo:
    image: mongo:latest
    container_name: bot-mongo
    ports:
      - "27017:27017"
    volumes:
      - myvolume:/data/db
    networks:
      - mynetwork

  discord-bot:
    build:
      context: .
    image: discord-bot:latest
    container_name: bot-client
    depends_on:
      - mongo
    networks:
      - mynetwork
    stdin_open: true
    tty: true
    entrypoint: ["bash", "-c", "cd /root/discord-bot && python3 client.py"]


volumes:
  myvolume:

networks:
  mynetwork: